### ISSUE TITLE
reCaptcha does not work

### ISSUE THREAD

**Issue by idnovic** [matthprost/scaleway-manager#27]
I can not login because the reCaptcha does not work.

`ERROR for site owner: Invalid site key`

**Comment by tarbib** [comment]
Same here

**Comment by VLNTNO** [comment]
Hello, I noticed the same issue here too, resulting in being unable to log in and test the application.
Best regards.

**Comment by idnovic** [comment]
I tested the newest update and the captcha is very slow. 
I also can not successfully log in because I am not asked for 2fa. 
This may be a scaleway issue. Because the captcha is also very slow at the website.

**Comment by matthprost** [comment]
Hello @idnovic, I made another update since then it seemed that the 2fa didn't properly work due to some internal configuration. For the captcha it can indeed be slow, I don't know exactly how does it work but it seems that if your IP has made many requests onto it, it will be slower.

You can find the new version here: https://github.com/matthprost/scaleway-manager/releases/tag/2.4.1

Or download it directly from Apple Store or Google Play Store

**Comment by VLNTNO** [comment]
That's OK for me, after the update deployed on the Google Play Store I could enjoy your application.
Cheers!
